Merged in wb-cb4-86 (pull request #277)
Wb cb4 86

* testing

* testing

* test

* test

* tested

* tested

* Merged in wb-cb4-19 (pull request #284)

Wb cb4 19 [DEPLOY]

* tested

* Merged in wb-cb4-19 (pull request #285)

tested [DEPLOY]

* tested

* tested

* Merged in wb-cb4-19 (pull request #287)

Wb cb4 19 [DEPLOY]

* tested

* Merged in wb-cb4-19 (pull request #289)

tested [DEPLOY]

* Ready

* Ready

* updated pipeline

* updated pipeline

* updated pipeline

* Merged in wb-cb4-86 (pull request #292)

Wb cb4 86 [DEPLOY]

* updated pipeline

* Merged in wb-cb4-86 (pull request #293)

updated pipeline [DEPLOY]

* updated pipeline

* updated pipeline

* updated pipeline


Approved-by: Yadukrishnan Perumpillil

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -59,24 +59,37 @@ definitions:
         COMMIT_MSG=$(git log -1 --pretty=%B)
         echo "Latest commit message: ${COMMIT_MSG}"
 
+        if [ -f ".lambda_version" ]; then
+          export LAMBDA_VERSION=$(cat .lambda_version)
+        else
+          echo "[ERROR] Lambda version not found. Please run zip_and_upload_lambdas first."
+          exit 1
+        fi
+
         if echo "${COMMIT_MSG}" | grep -q "\[DEPLOY\]" || [ "$BITBUCKET_BRANCH" == "develop" ]; then
           echo "DEPLOY keyword found in commit. Proceeding..."
           BRANCH_NAME=$(echo "$BITBUCKET_BRANCH" | tr '/' '-')
           STACK_NAME="${BRANCH_NAME}-deployment"
+          TEMPLATE_FILE="Templates/Resources/deploy.yaml"
+          S3_BUCKET="service-workbench-artifacts"
+          S3_KEY="cf/${BRANCH_NAME}/deploy.yaml"
 
-          if [ ! -f "Templates/Resources/deploy.yaml" ]; then
-            echo "[ERROR] Templates/Resources/deploy.yaml not found"
-            exit 1
-          fi
+
+          # if [ ! -f "Templates/Resources/deploy.yaml" ]; then
+          #   echo "[ERROR] Templates/Resources/deploy.yaml not found"
+          #   exit 1
+          # fi
 
           chmod +x Scripts/swagger-replacement.sh
           ./Scripts/swagger-replacement.sh "${BRANCH_NAME}"
           
           aws cloudformation deploy \
-            --template-file Templates/Resources/deploy.yaml \
+            --template-file "$TEMPLATE_FILE" \
             --stack-name "$STACK_NAME" \
             --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM \
             --parameter-overrides pPrefix="${BRANCH_NAME}" pRAGPrefix="${BRANCH_NAME//-/_}" DeploymentTrigger="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
+            --s3-bucket "${S3_BUCKET}" \
+            --s3-prefix "cf/${BRANCH_NAME}" \
             --no-fail-on-empty-changeset || {
               echo "[ERROR] CloudFormation deployment failed"
               exit 1
@@ -100,22 +113,52 @@ definitions:
           exit 1
         fi
 
-        if [ ! -f "Templates/Resources/infra.yaml" ]; then
-          echo "[ERROR] Templates/Resources/infra.yaml not found"
-          exit 1
-        fi
+        # if [ ! -f "Templates/Resources/infra.yaml" ]; then
+        #   echo "[ERROR] Templates/Resources/infra.yaml not found"
+        #   exit 1
+        # fi
 
         STACK_NAME="${BRANCH_NAME}-infra"
+        TEMPLATE_FILE="Templates/Resources/infra.yaml"
+        S3_BUCKET="service-workbench-artifacts"
+        S3_KEY="cf/${BRANCH_NAME}/infra.yaml"
         echo "Deploying infrastructure stack: $STACK_NAME"
 
         aws cloudformation deploy \
-          --template-file Templates/Resources/infra.yaml \
+          --template-url "$TEMPLATE_FILE" \
           --stack-name "$STACK_NAME" \
           --capabilities CAPABILITY_NAMED_IAM \
+          --s3-bucket "${S3_BUCKET}" \
+          --s3-prefix "cf/${BRANCH_NAME}" \
           --parameter-overrides pApplicationPrefix="${BRANCH_NAME}" || {
             echo "[ERROR] Infra deployment failed"
             exit 1
           }
+
+    - script: &upload_cf_templates
+        |
+        set -e
+        echo "Uploading CloudFormation templates to S3..."
+        
+        CF_S3_BUCKET="service-workbench-artifacts"
+        BRANCH_NAME=$(echo "$BITBUCKET_BRANCH" | tr '/' '-')
+
+        for TEMPLATE in Templates/Resources/deploy.yaml Templates/Resources/infra.yaml; do
+          if [ -f "$TEMPLATE" ]; then
+            FILE_NAME=$(basename "$TEMPLATE")
+            S3_KEY="cf/${BRANCH_NAME}/${FILE_NAME}"
+            echo "Uploading $TEMPLATE to s3://${CF_S3_BUCKET}/${S3_KEY}"
+            aws s3 cp "$TEMPLATE" "s3://${CF_S3_BUCKET}/${S3_KEY}" || {
+              echo "[ERROR] Failed to upload $TEMPLATE"
+              exit 1
+            }
+          else
+            echo "[WARN] Template not found: $TEMPLATE"
+          fi
+        done
+
+        echo "CloudFormation templates uploaded successfully."
+
 
     - script: &build_ui
         |
@@ -336,10 +379,21 @@ definitions:
 
         mkdir -p "$LAMBDA_ZIP_DIR"
         trap "rm -rf $LAMBDA_ZIP_DIR" EXIT
+        LAMBDA_VERSION=$(date -u +"%Y%m%dT%H%M%SZ")
+        echo "Using Lambda version: $LAMBDA_VERSION"
+        export LAMBDA_VERSION
+        echo "$LAMBDA_VERSION" > .lambda_version
         for CATEGORY in "$BASE_DIR"/*; do
           if [ -d "$CATEGORY" ]; then
             CATEGORY_NAME=$(basename "$CATEGORY")
+
+            echo "Cleaning up old lambda zips for: ${CATEGORY_NAME,,}"
+            aws s3 rm "s3://${DEST_BUCKET}/" --recursive --exclude "*" --include "lambda-*/${CATEGORY_NAME,,}/*.zip" || true
+
+
+            # S3_PREFIX="lambda-${LAMBDA_VERSION}/${CATEGORY_NAME,,}"
             S3_PREFIX="lambda/${CATEGORY_NAME,,}"
+
             # Get all .py files in the category
             mapfile -t PY_FILES < <(find "$CATEGORY" -maxdepth 1 -type f -name "*.py")
             if [ ${#PY_FILES[@]} -eq 0 ]; then
@@ -624,6 +678,8 @@ definitions:
           - echo "Starting deployment process..."
           - *authenticate
           - *deploy_stack
+        artifacts:
+          - .lambda_version
 
     - step: &deploy_infra_stack
         name: Deploy Infrastructure
@@ -666,6 +722,8 @@ definitions:
           - echo "Zipping and uploading lambda files..."
           - *authenticate
           - *zip_and_upload_lambdas
+        artifacts:
+          - .lambda_version
 
     - step: &update_branch_lambdas
         name: Update Branch Lambda Functions
@@ -674,6 +732,14 @@ definitions:
           - echo "Updating Lambda functions for current branch..."
           - *authenticate
           - *update_branch_specific_lambdas
+    
+    - step: &update_cftemplates
+        name: Upload CloudFormation Templates
+        oidc: true
+        script:
+          - echo "Uploading CloudFormation templates to S3..."
+          - *authenticate
+          - *upload_cf_templates
 
 pipelines:
   branches:
@@ -681,6 +747,7 @@ pipelines:
       - step: *lint_and_validate
       - step: *zipping_and_uploading_layers
       - step: *zipping_and_uploading_lambdas
+      - step: *update_cftemplates
       - step: *deploy
       - step: *build_and_deploy_ui
 
@@ -688,6 +755,7 @@ pipelines:
       - step: *lint_and_validate
       - step: *zipping_and_uploading_layers
       - step: *zipping_and_uploading_lambdas
+      - step: *update_cftemplates
       - step: *deploy
       - step: *build_and_deploy_ui
       
@@ -695,6 +763,7 @@ pipelines:
       - step: *lint_and_validate
       - step: *zipping_and_uploading_layers
       - step: *zipping_and_uploading_lambdas
+      - step: *update_cftemplates
       - step: *deploy
       - step: *build_and_deploy_ui
 
@@ -702,6 +771,7 @@ pipelines:
       - step: *lint_and_validate
       - step: *zipping_and_uploading_layers
       - step: *zipping_and_uploading_lambdas
+      - step: *update_cftemplates
       - step: *deploy
       - step: *build_and_deploy_ui
 
@@ -712,6 +782,7 @@ pipelines:
       - step: *lint_and_validate
       - step: *zipping_and_uploading_layers
       - step: *zipping_and_uploading_lambdas
+      - step: *upload_cf_templates
       - step: *deploy
       - step: *deploy_infra_stack
       - step: *build_and_deploy_ui
