added files in Web folder [DEPLOY]

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -80,7 +80,13 @@ definitions:
             }
 
           echo "Waiting for stack creation..."
-          aws cloudformation wait stack-create-complete --stack-name "$STACK_NAME"
+          # aws cloudformation wait stack-create-complete --stack-name "$STACK_NAME"
+          if ! aws cloudformation wait stack-update-complete --stack-name "$STACK_NAME"; then
+            aws cloudformation wait stack-create-complete --stack-name "$STACK_NAME" || {
+              echo "[ERROR] Stack creation or update failed"
+              exit 1
+            }
+          fi
           echo "API deployment completed successfully."
         else
           echo "Skipping deployment: No DEPLOY keyword in commit message."
@@ -252,7 +258,7 @@ pipelines:
           script:
             - echo "Manual trigger from branch: ${BITBUCKET_BRANCH}"
             - *authenticate
-            - *deploy_infra_stack
+            - *deploy_infra
 
     UI-setup:
       - step:
